max_width = 120
use_small_heuristics = "Max"
short_array_element_width_threshold = 16
comment_width = 110
# tab_spaces = 2
tab_spaces = 4

brace_style = "PreferSameLine"
combine_control_expr = true
fn_single_line = true

format_macro_matchers = false
wrap_comments = true
format_strings = true

imports_indent = "Visual"
# indent_style = "Visual"
match_arm_blocks = false
struct_lit_single_line = true

match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = false
trailing_comma = "Never"

imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"

unstable_features = true

use_field_init_shorthand = true
