[package]
name = "rusty-crab"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "ssh://git@github.com/unitn-ap-2025/common.git" }
crossbeam-channel = "0.5.15"
chrono = "0.4.42"
log = "0.4.29"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
fern = { version = "0.7.1", features = ["colored"] }
config = "0.15.19"

[[bin]]
name = "rusty-crab"
path = "src/lib.rs"
