[package]
name = "rusty-crab"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "ssh://git@github.com/unitn-ap-2025/common.git" }

[[bin]]
name = "rusty-crab"
path = "src/lib.rs"